### PR TITLE
吳承澤 merge between Develop and main

### PR DESCRIPTION
**Pull request by ChengTze-Wu**
彭彭老師好，這是本週作業，再麻煩老師審查了！
http://35.72.240.231:3000/
http://35.72.240.231:3000/attraction/7
http://35.72.240.231:3000/booking

### CODE REVIEW

**Comment by cwpeng** [comment]
I add different attractions to booking twice, and delete one, you will show another one. But if we only support 1 attraction in booking, when we delete it, it should be empty.

**Comment by ChengTze-Wu** [comment]
修正好了～麻煩老師再審查

**Comment by ChengTze-Wu** [comment]
修正好了～請老師再審～

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
